### ISSUE TITLE
Memory usage - lift apply

### ISSUE THREAD

**Issue by andrewk8** [Aries85/LightZone#167]
When performing lift / apply to a large number of images in a folder, memory usage is excessive.  LightZone keeps grabbing memory until it's all used up, then it crashes.

Workaround:  lift / apply to a smaller number of images to stay below the memory limit.  Exit LightZone.  Open LightZone, and continue lift / apply.  Repeat as many times as necessary until apply has been performed to all the images in the folder.

It is like LightZone is caching in RAM all the images in the folder.

Issue present in 4.1.4 on Windows x64

**Comment by ktgw0316** [comment]
I checked heap memory usage using Java VisualVM, and I found that LZ worked normally if I **lower** memory limit to 512MB in LZ (Edit > Preferences... > Memory Limit) because heap was released by GC before reaching the limit. On the other hand, If the limit was 2GB on the same PC which memory is 4G, the heap usage continuously increased and LZ froze time to time.

**Comment by ktgw0316** [comment]
Commits b23972b and 4f2b6c6 fix this issue.
