### ISSUE TITLE
"Invalid image file" after uppgrading to fw4 with fuji x-e2

### ISSUE THREAD

**Issue by R00S** [Aries85/LightZone#170]
After uppgrading to firmware 4 on my fuji x-e2, the raw files produced by the camera can no longer be opened by lightzone (4.1.5). A popup with the text "Invalid image file" and the path to the files is opened when the files are clicked.

**Comment by arangast** [comment]
Hello, I wanted to try LightZone out for the first time too and have the same problem with firmware 4. The problem is because the RAF header has changed and dcraw is reading it incorrectly. I contacted the author and he gave me a patch:

The fix involves replacing the following line in parse_fuji:
if ((tag = get4()) > 10000) tag = get4();

...with:
while ((tag = get4()) > 10000);

If you want to test it out, you can find a broken RAF file here:
https://www.dropbox.com/s/kzi1o44gh0t5s1j/20160204-7859.raf?dl=0

Cheers!

**Comment by ktgw0316** [comment]
I tested the patch and it worked like a charm. Thank you very much!

**Comment by arangast** [comment]
Great, do you have any idea when it could be included in a build?

Otherwise are there instructions for building for windows from scratch?

**Comment by ktgw0316** [comment]
I think I can release new version in next week, after fixing another bug on Mac OS X.

There is an instruction in `windows/BUILD-Windows.md`. but the setup is really complicated.
