### ISSUE TITLE
colors wrong

### ISSUE THREAD

**Issue by andrewk8** [Aries85/LightZone#206]
Using LZ 4.1.7 on Windows 10 x64.
Editing a folder of photos and they all look yellow-ish.  Did a white balance and they still look yellow-ish. Saved the file and opened the LZ file with Windows Photos - white balance looked right.  Opened the LZ file with GIMP 2.8.22 - white balance looked right.  Moved the Windows Photos, Corel Paint Shop Pro, and GIMP windows on top of LZ - LZ is definitely yellow.  GIMP gives a visually white-ish point as RGB 228,228,229.  So "looks like a neutral point" really is "IS an neutral point", and LZ-only is showing a weird color shift towards yellow.
![3tyhynv](https://user-images.githubusercontent.com/16465258/32306496-14423d80-bf52-11e7-806d-17b39394ef14.jpg)
[sample.zip](https://github.com/Aries85/LightZone/files/1436271/sample.zip)

**Comment by ktgw0316** [comment]
I compared the renderings in Gimp (2.8.10, default settings) and LZ (4.1.7) on my Windows 10 (x64) laptop. As you said, they have color difference.

Gimp:
![gimp-without-prof](https://user-images.githubusercontent.com/3116763/33664272-5ea44a04-dad6-11e7-85d9-4bde6dd2a442.PNG)
LZ:
![lz](https://user-images.githubusercontent.com/3116763/33664276-5f138932-dad6-11e7-8e69-bd86eca06d0a.PNG)

However, when I turned on "Try to use the system monitor profile" in Edit > Preferences > Color Management in Gimp, it showed the image just like LZ,
![gimp-settings](https://user-images.githubusercontent.com/3116763/33664271-5e75c36e-dad6-11e7-8e01-3f5f261aff00.PNG)
![gimp-with-prof](https://user-images.githubusercontent.com/3116763/33664274-5edaf6c6-dad6-11e7-9434-7460ab947617.PNG)

I also checked Chrome (62.0.3202.94) for .jpg file, because I think that web browsers are reliable in color rendering:
![chrome](https://user-images.githubusercontent.com/3116763/33664270-5e45568e-dad6-11e7-98a0-e5172c063328.PNG)

Windows Photo:
![windowsphoto](https://user-images.githubusercontent.com/3116763/33664277-5f40a73c-dad6-11e7-822d-f0fdddb11a9b.PNG)

So, I don't think it is a bug in LZ. I guess Windows Photo is not color-managed. I have no idea about Corel Paint Shop Pro,

Masahiro
