### ISSUE TITLE
Strange black band in image

### ISSUE THREAD

**Issue by juhavlintula** [Aries85/LightZone#233]
Lightzone with latest patches (750073c) generates a strange black band in one of my images.
![screenshot from 2018-09-06 23-11-13](https://user-images.githubusercontent.com/18402158/45182555-4fae6580-b22a-11e8-8991-50919a342815.png)
If I open the TIFF there is no band in the editing window.

When I opened the original ORF file in my older Ubuntu laptop, the band was also visible in the editing window and it was saved in the lzn file. When I edited the image in my Virtualbox Ubuntu (with the same version of Lightzone) or in Win10 with the Jan release, there was no band.

The problem file is in my [Dropbox](https://www.dropbox.com/sh/q4r3vx3prw2pl4b/AAABn0WNkaakNG9Xs4TTKTVHa?dl=0), image P7140726.

**Comment by 61616** [comment]
I'm having this issue too. I'm running version 4.2.0 (1521dcc). I can't find a log or debug anywhere, otherwise I would post that, let me know if there's some way to access that.
![LZ BUG 2 2020-05-25 121734](https://user-images.githubusercontent.com/33187059/82829660-d1707780-9e81-11ea-8855-6a33922795ef.jpg)
![LZ Bug 2020-05-25 121702](https://user-images.githubusercontent.com/33187059/82829695-e2b98400-9e81-11ea-9200-7fd0a2504107.jpg)

**Comment by ktgw0316** [comment]
@61616 I think this issue is fixed in v4.2.1, which can be downloaded from https://github.com/ktgw0316/LightZone/releases/tag/4.2.1
